# Site settings
title: Cat Codes
header-img: img/home-bg.png
email: catglenn4@gmail.com
copyright_name: CatGlenn
description: > # this means to ignore newlines until "baseurl:"
  Creativity and Computer Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CatGlenn
learn_profile: CatGlenn
email_username: catglenn4@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
